name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          dcjoker/csp451-web:latest
          dcjoker/csp451-web:${{ github.ref_name }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          docker-compose.yml
          init.sql
        body: |
          Release ${{ github.ref_name }}
          
          ## Deployment Instructions
          
          1. Download the `docker-compose.yml` and `init.sql` files
          2. Run `docker-compose up -d`
          3. Access the application at http://localhost:3000
          
          For more details, see the [deployment documentation](../../README.md#production-deployment)
